# Core Loader — one-click install (Windows PowerShell)
# Usage:
#   irm https://raw.githubusercontent.com/coreloader/coreloader/main/install.ps1 | iex
#   .\install.ps1 -Version v8.0.0 -Php 8.3
param(
  [string]$Owner = $(if ($env:CORELOADER_GH_OWNER) { $env:CORELOADER_GH_OWNER } else { "coreloader" }),
  [string]$Repo = $(if ($env:CORELOADER_GH_REPO) { $env:CORELOADER_GH_REPO } else { "coreloader" }),
  [string]$Version = $(if ($env:CORELOADER_VERSION) { $env:CORELOADER_VERSION } else { "latest" }),
  [string]$Php = "",
  [string]$PhpBin = "",
  [string]$Dir = "",
  [string]$Ini = "",
  [switch]$NoIni,
  [switch]$DryRun,
  [switch]$Force
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Owner) -or [string]::IsNullOrWhiteSpace($Repo)) {
  Write-Error "Owner/Repo must not be empty"
}

function Get-PhpVersionFromBin([string]$bin) {
  $out = & $bin -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;" 2>$null
  if (-not $out) { throw "php not found: $bin" }
  return $out.Trim()
}

function Get-WinArch {
  if ([Environment]::Is64BitProcess) { return "x64" }
  return "x86"
}

function Get-ExtensionDir([string]$bin) {
  if ($Dir) { return $Dir }
  $ext = & $bin -r "echo ini_get('extension_dir');" 2>$null
  if ($ext -and $ext.Trim() -ne "." -and $ext.Trim() -ne "") {
    return $ext.Trim()
  }
  throw "Could not detect extension_dir; pass -Dir"
}

function Get-IniTarget([string]$bin) {
  if ($Ini) { return $Ini }
  $iniOut = & $bin --ini 2>$null | Out-String
  $loaded = $null
  $scan = $null
  foreach ($line in ($iniOut -split "`n")) {
    if ($line -match '^Loaded Configuration File:\s*(.+)$') { $loaded = $Matches[1].Trim() }
    if ($line -match '^Scan for additional \.ini files in:\s*(.+)$') { $scan = $Matches[1].Trim() }
  }
  if ($scan -and $scan -ne '(none)' -and $scan -ne 'none') {
    return (Join-Path $scan '99-core_loader.ini')
  }
  if ($loaded -and $loaded -ne '(none)' -and $loaded -ne 'none') {
    return $loaded
  }
  throw "Could not detect php.ini; pass -Ini"
}

function Update-PhpIni([string]$path, [string]$line, [string]$destName) {
  $dir = Split-Path -Parent $path
  if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }

  if ((Split-Path -Leaf $path) -eq '99-core_loader.ini') {
    $content = "; Generated by coreloader install.ps1 — do not use zend_extension=`r`n$line`r`n"
    Set-Content -Path $path -Value $content -Encoding ASCII
    Write-Host "  ini: wrote $path"
    return
  }

  $text = ""
  if (Test-Path $path) {
    $text = Get-Content -Path $path -Raw -ErrorAction SilentlyContinue
    if ($null -eq $text) { $text = "" }
  }

  if ($text -match "(?m)^\s*extension\s*=\s*(php_)?core_loader(\.dll)?\b") {
    Write-Host "  ini: already enabled in $path"
    return
  }

  $text = [regex]::Replace($text, '(?m)^(\s*)zend_extension\s*=\s*.*core_loader.*$', ';${1} disabled by coreloader install (use extension=)')
  if (-not ($text.EndsWith("`n") -or $text.Length -eq 0)) { $text += "`r`n" }
  $text += "`r`n; Core Loader (auto)`r`n$line`r`n"
  Set-Content -Path $path -Value $text -Encoding ASCII -NoNewline
  Write-Host "  ini: updated $path"
}

if (-not $PhpBin) { $PhpBin = "php" }
if (-not $Php) { $Php = Get-PhpVersionFromBin $PhpBin }

$supported = @("7.0","7.1","7.2","7.3","7.4","8.0","8.1","8.2","8.3","8.4","8.5")
if ($supported -notcontains $Php) {
  throw "Unsupported PHP version '$Php' (supported: 7.0–8.5). Hint: -Version is the Release tag (v8.0.0); use -Php 8.3 for PHP version."
}

$arch = Get-WinArch
$asset = "php_core_loader-php${Php}-win-${arch}.dll"
$destName = "php_core_loader.dll"
$installDir = Get-ExtensionDir $PhpBin
$iniLine = "extension=$destName"

$iniPath = $null
if (-not $NoIni) {
  $iniPath = Get-IniTarget $PhpBin
}

if ($Version -eq "latest") {
  $url = "https://github.com/$Owner/$Repo/releases/latest/download/$asset"
} else {
  $tag = if ($Version.StartsWith("v")) { $Version } else { "v$Version" }
  $url = "https://github.com/$Owner/$Repo/releases/download/$tag/$asset"
}

$dest = Join-Path $installDir $destName

Write-Host "Core Loader install"
Write-Host "  PHP:     $Php ($PhpBin)"
Write-Host "  Arch:    win-$arch"
Write-Host "  Asset:   $asset"
Write-Host "  From:    $url"
Write-Host "  To:      $dest"
if ($NoIni) {
  Write-Host "  Ini:     (skipped)"
} else {
  Write-Host "  Ini:     $iniPath"
}

if ($DryRun) {
  Write-Host "[dry-run] skip download/install/ini"
  exit 0
}

# Always overwrite existing extension

$tmp = Join-Path $env:TEMP ("core_loader_" + [guid]::NewGuid().ToString() + ".dll")
try {
  Invoke-WebRequest -Uri $url -OutFile $tmp -UseBasicParsing
  $fs = [System.IO.File]::OpenRead($tmp)
  try {
    $b0 = $fs.ReadByte(); $b1 = $fs.ReadByte()
  } finally { $fs.Close() }
  if ($b0 -ne 0x4D -or $b1 -ne 0x5A) {
    throw "Downloaded file is not a PE DLL"
  }

  if (-not (Test-Path $installDir)) {
    New-Item -ItemType Directory -Path $installDir -Force | Out-Null
  }
  Copy-Item -Force $tmp $dest
} catch {
  Write-Host "Install failed: $_"
  Write-Host "Run PowerShell as Administrator if permission denied."
  throw
} finally {
  if (Test-Path $tmp) { Remove-Item -Force $tmp }
}

Write-Host "Installed: $dest"

if (-not $NoIni) {
  Write-Host "Configuring PHP..."
  Update-PhpIni -path $iniPath -line $iniLine -destName $destName
}

Write-Host ""
Write-Host "Verify:"
Write-Host "  $PhpBin -m | findstr core_loader"
Write-Host "  $PhpBin -r `"var_export(extension_loaded('core_loader')); echo PHP_EOL;`""
